# config.yaml
seed: 42

# Data generation parameters
data:
  num_classes: 16
  num_samples: 65536
  image_size: [3, 224, 224]
  formats: ['png', 'arrow', 'parquet', 'npy']
  # formats: ['parquet']
  root_dir: '/mnt/pvc/data_read_benchmark/data/generated_data'
  parquet_batch_size: 4096

# Dataloader parameters
dataloader:
  batch_size: [64, 128, 256]
  num_workers: [0, 4, 8]

# PyTorch Lightning Trainer parameters
trainer:
  gpus_configs:
    # - [0] # single-gpu case
    - [0, 1, 2, 3, 4, 5, 6, 7] # multi-gpu case, uncomment if you have multiple GPUs
  max_epochs: 1

# Wandb logging parameters
wandb:
  project: 'data-read-benchmark'
  entity: null # Your wandb entity
